**Pivot Tables

In [1]:
import pandas as pd
import numpy as np

In [2]:
%ls datasets/

adult.csv                  census.csv     movies.csv
airline_data.csv           coches.csv     nhanes_2015_2016.csv
antropometria00.csv        cwurData.csv   pokemon.csv
antropometria-dataset.csv  data.csv       reg_data.csv
Book3.csv                  headbrain.csv  sample_pivot.csv
Canada.xlsx                mic2.xlsx      tips.csv
Cartwheeldata.csv          mic.xlsx       weight-height.csv

In [4]:
df = pd.read_csv("datasets/census.csv")
df.head(2)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333

In [5]:
df.describe()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
count,3193.000000,3193.000000,3193.000000,3193.000000,3193.000000,3.193000e+03,3.193000e+03,3.193000e+03,3.193000e+03,3.193000e+03,...,3193.000000,3193.000000,3193.000000,3193.000000,3193.000000,3193.000000,3193.000000,3193.000000,3193.000000,3193.000000
mean,49.840276,2.668650,5.191356,30.259004,101.918572,1.933871e+05,1.933969e+05,1.937657e+05,1.952514e+05,1.967445e+05,...,-1.639167,-2.528381,-1.288083,-2.271925,-1.362607,-0.655205,-1.445775,-0.200419,-1.038960,-0.096759
std,1.253884,0.807513,1.973991,15.153897,107.626583,1.176201e+06,1.176244e+06,1.178710e+06,1.189648e+06,1.200508e+06,...,10.407267,11.871798,12.186844,11.440505,12.301558,10.613259,12.228155,12.200064,11.471743,12.265772
min,40.000000,1.000000,1.000000,1.000000,0.000000,8.200000e+01,8.200000e+01,8.300000e+01,9.000000e+01,8.100000e+01,...,-128.205128,-147.727273,-109.876862,-178.947368,-84.844838,-128.205128,-147.727273,-102.988031,-178.947368,-62.322703
25%,50.000000,2.000000,4.000000,18.000000,33.000000,1.129900e+04,1.129900e+04,1.127500e+04,1.127700e+04,1.119500e+04,...,-6.153101,-7.561799,-6.323058,-7.357497,-6.696825,-5.354221,-6.851764,-5.426357,-6.221820,-5.553088
50%,50.000000,3.000000,5.000000,29.000000,77.000000,2.642400e+04,2.644600e+04,2.646700e+04,2.641700e+04,2.636200e+04,...,-1.544618,-2.549859,-1.771445,-1.988101,-2.026566,-0.626174,-1.537988,-0.788296,-0.911948,-0.872527
75%,50.000000,3.000000,7.000000,45.000000,133.000000,7.140400e+04,7.149100e+04,7.172100e+04,7.238700e+04,7.249600e+04,...,2.901204,2.626611,3.392786,3.333927,3.794291,4.062151,3.962629,4.700873,4.580444,5.013928
max,50.000000,4.000000,9.000000,56.000000,840.000000,3.725396e+07,3.725450e+07,3.733408e+07,3.770003e+07,3.805606e+07,...,101.123596,119.193807,239.130435,146.367943,281.407035,101.123596,119.861185,239.130435,146.960126,281.407035

In [11]:
x = df.columns.tolist()
x.sort()
x

['BIRTHS2010',
 'BIRTHS2011',
 'BIRTHS2012',
 'BIRTHS2013',
 'BIRTHS2014',
 'BIRTHS2015',
 'CENSUS2010POP',
 'COUNTY',
 'CTYNAME',
 'DEATHS2010',
 'DEATHS2011',
 'DEATHS2012',
 'DEATHS2013',
 'DEATHS2014',
 'DEATHS2015',
 'DIVISION',
 'DOMESTICMIG2010',
 'DOMESTICMIG2011',
 'DOMESTICMIG2012',
 'DOMESTICMIG2013',
 'DOMESTICMIG2014',
 'DOMESTICMIG2015',
 'ESTIMATESBASE2010',
 'GQESTIMATES2010',
 'GQESTIMATES2011',
 'GQESTIMATES2012',
 'GQESTIMATES2013',
 'GQESTIMATES2014',
 'GQESTIMATES2015',
 'GQESTIMATESBASE2010',
 'INTERNATIONALMIG2010',
 'INTERNATIONALMIG2011',
 'INTERNATIONALMIG2012',
 'INTERNATIONALMIG2013',
 'INTERNATIONALMIG2014',
 'INTERNATIONALMIG2015',
 'NATURALINC2010',
 'NATURALINC2011',
 'NATURALINC2012',
 'NATURALINC2013',
 'NATURALINC2014',
 'NATURALINC2015',
 'NETMIG2010',
 'NETMIG2011',
 'NETMIG2012',
 'NETMIG2013',
 'NETMIG2014',
 'NETMIG2015',
 'NPOPCHG_2010',
 'NPOPCHG_2011',
 'NPOPCHG_2012',
 'NPOPCHG_2013',
 'NPOPCHG_2014',
 'NPOPCHG_2015',
 'POPESTIMATE2010',
 'POPESTIMATE2011',
 'POPESTIMATE2012',
 'POPESTIMATE2013',
 'POPESTIMATE2014',
 'POPESTIMATE2015',
 'RBIRTH2011',
 'RBIRTH2012',
 'RBIRTH2013',
 'RBIRTH2014',
 'RBIRTH2015',
 'RDEATH2011',
 'RDEATH2012',
 'RDEATH2013',
 'RDEATH2014',
 'RDEATH2015',
 'RDOMESTICMIG2011',
 'RDOMESTICMIG2012',
 'RDOMESTICMIG2013',
 'RDOMESTICMIG2014',
 'RDOMESTICMIG2015',
 'REGION',
 'RESIDUAL2010',
 'RESIDUAL2011',
 'RESIDUAL2012',
 'RESIDUAL2013',
 'RESIDUAL2014',
 'RESIDUAL2015',
 'RINTERNATIONALMIG2011',
 'RINTERNATIONALMIG2012',
 'RINTERNATIONALMIG2013',
 'RINTERNATIONALMIG2014',
 'RINTERNATIONALMIG2015',
 'RNATURALINC2011',
 'RNATURALINC2012',
 'RNATURALINC2013',
 'RNATURALINC2014',
 'RNATURALINC2015',
 'RNETMIG2011',
 'RNETMIG2012',
 'RNETMIG2013',
 'RNETMIG2014',
 'RNETMIG2015',
 'STATE',
 'STNAME',
 'SUMLEV']

In [27]:
pd.pivot_table(df,
               index = ['STNAME','CTYNAME'],
               aggfunc = ['median'],
               values = ['BIRTHS2010','BIRTHS2011'],
               margins = True,
               columns = 'SUMLEV'
              )

                            median
                        BIRTHS2010               BIRTHS2011
SUMLEV                          40     50    All         40      50    All
STNAME  CTYNAME
Alabama Alabama            14226.0    NaN  14226    59689.0     NaN  59689
        Autauga County         NaN  151.0    151        NaN   636.0    636
        Baldwin County         NaN  517.0    517        NaN  2187.0   2187
        Barbour County         NaN   70.0     70        NaN   335.0    335
        Bibb County            NaN   44.0     44        NaN   266.0    266
...                            ...    ...    ...        ...     ...    ...
Wyoming Uinta County           NaN   73.0     73        NaN   324.0    324
        Washakie County        NaN   26.0     26        NaN   108.0    108
        Weston County          NaN   26.0     26        NaN    81.0     81
        Wyoming             1995.0    NaN   1995     7471.0     NaN   7471
All                        13752.0   76.0     78    55313.0   304.0    311

[3193 rows x 6 columns]

In [19]:
df['BIRTHS2010'].describe()

count      3193.000000
mean        618.751018
std        3838.926925
min           0.000000
25%          31.000000
50%          78.000000
75%         216.000000
max      123324.000000
Name: BIRTHS2010, dtype: float64

In [28]:
%ls datasets/

adult.csv                  census.csv     movies.csv
airline_data.csv           coches.csv     nhanes_2015_2016.csv
antropometria00.csv        cwurData.csv   pokemon.csv
antropometria-dataset.csv  data.csv       reg_data.csv
Book3.csv                  headbrain.csv  sample_pivot.csv
Canada.xlsx                mic2.xlsx      tips.csv
Cartwheeldata.csv          mic.xlsx       weight-height.csv

In [44]:
adf = pd.read_csv('datasets/airline_data.csv', low_memory = False)

In [45]:
x = adf.columns.tolist()
x.sort()
x

['ActualElapsedTime',
 'AirTime',
 'ArrDel15',
 'ArrDelay',
 'ArrDelayMinutes',
 'ArrTime',
 'ArrTimeBlk',
 'ArrivalDelayGroups',
 'CRSArrTime',
 'CRSDepTime',
 'CRSElapsedTime',
 'CancellationCode',
 'Cancelled',
 'CarrierDelay',
 'DOT_ID_Reporting_Airline',
 'DayOfWeek',
 'DayofMonth',
 'DepDel15',
 'DepDelay',
 'DepDelayMinutes',
 'DepTime',
 'DepTimeBlk',
 'DepartureDelayGroups',
 'Dest',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'DestCityName',
 'DestState',
 'DestStateFips',
 'DestStateName',
 'DestWac',
 'Distance',
 'DistanceGroup',
 'Div1Airport',
 'Div1AirportID',
 'Div1AirportSeqID',
 'Div1LongestGTime',
 'Div1TailNum',
 'Div1TotalGTime',
 'Div1WheelsOff',
 'Div1WheelsOn',
 'Div2Airport',
 'Div2AirportID',
 'Div2AirportSeqID',
 'Div2LongestGTime',
 'Div2TailNum',
 'Div2TotalGTime',
 'Div2WheelsOff',
 'Div2WheelsOn',
 'Div3Airport',
 'Div3AirportID',
 'Div3AirportSeqID',
 'Div3LongestGTime',
 'Div3TailNum',
 'Div3TotalGTime',
 'Div3WheelsOff',
 'Div3WheelsOn',
 'Div4Airport',
 'Div4AirportID',
 'Div4AirportSeqID',
 'Div4LongestGTime',
 'Div4TailNum',
 'Div4TotalGTime',
 'Div4WheelsOff',
 'Div4WheelsOn',
 'Div5Airport',
 'Div5AirportID',
 'Div5AirportSeqID',
 'Div5LongestGTime',
 'Div5TailNum',
 'Div5TotalGTime',
 'Div5WheelsOff',
 'Div5WheelsOn',
 'DivActualElapsedTime',
 'DivAirportLandings',
 'DivArrDelay',
 'DivDistance',
 'DivReachedDest',
 'Diverted',
 'FirstDepTime',
 'FlightDate',
 'Flight_Number_Reporting_Airline',
 'Flights',
 'IATA_CODE_Reporting_Airline',
 'LateAircraftDelay',
 'LongestAddGTime',
 'Month',
 'NASDelay',
 'Origin',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'OriginCityName',
 'OriginState',
 'OriginStateFips',
 'OriginStateName',
 'OriginWac',
 'Quarter',
 'Reporting_Airline',
 'SecurityDelay',
 'Tail_Number',
 'TaxiIn',
 'TaxiOut',
 'TotalAddGTime',
 'Unnamed: 0',
 'WeatherDelay',
 'WheelsOff',
 'WheelsOn',
 'Year']

1. What is the minimum and maximum delay of airlines?

In [48]:
#'DepDelay', 'DepartureDelayGroups',
adf.loc[:, 'DepDelay'].max()

988.0

In [54]:
#pd.set_option('display.max_rows', 5000)

In [55]:
adf.groupby(['DepDelay', 'DepartureDelayGroups']).size()

DepDelay  DepartureDelayGroups
-23.0     -2.0                       1
-19.0     -2.0                       2
-18.0     -2.0                       1
-17.0     -2.0                       3
-16.0     -2.0                       6
-15.0     -1.0                      12
-14.0     -1.0                      11
-13.0     -1.0                      20
-12.0     -1.0                      20
-11.0     -1.0                      42
-10.0     -1.0                     112
-9.0      -1.0                     131
-8.0      -1.0                     181
-7.0      -1.0                     240
-6.0      -1.0                     350
-5.0      -1.0                     495
-4.0      -1.0                     538
-3.0      -1.0                     601
-2.0      -1.0                     705
-1.0      -1.0                     673
 0.0       0.0                    1468
 1.0       0.0                     324
 2.0       0.0                     264
 3.0       0.0                     222
 4.0       0.0                     189
 5.0       0.0                     181
 6.0       0.0                     133
 7.0       0.0                     119
 8.0       0.0                     126
 9.0       0.0                      94
 10.0      0.0                     104
 11.0      0.0                      79
 12.0      0.0                      76
 13.0      0.0                      72
 14.0      0.0                      68
 15.0      1.0                      69
 16.0      1.0                      59
 17.0      1.0                      51
 18.0      1.0                      48
 19.0      1.0                      51
 20.0      1.0                      62
 21.0      1.0                      43
 22.0      1.0                      52
 23.0      1.0                      32
 24.0      1.0                      22
 25.0      1.0                      40
 26.0      1.0                      33
 27.0      1.0                      30
 28.0      1.0                      37
 29.0      1.0                      26
 30.0      2.0                      36
 31.0      2.0                      17
 32.0      2.0                      18
 33.0      2.0                      29
 34.0      2.0                      22
 35.0      2.0                      28
 36.0      2.0                      23
 37.0      2.0                      17
 38.0      2.0                      15
 39.0      2.0                      16
 40.0      2.0                      27
 41.0      2.0                      15
 42.0      2.0                      15
 43.0      2.0                      26
 44.0      2.0                      23
 45.0      3.0                      22
 46.0      3.0                      10
 47.0      3.0                      11
 48.0      3.0                      11
 49.0      3.0                      15
 50.0      3.0                      14
 51.0      3.0                      11
 52.0      3.0                      17
 53.0      3.0                      12
 54.0      3.0                      15
 55.0      3.0                      15
 56.0      3.0                       9
 57.0      3.0                      12
 58.0      3.0                      12
 59.0      3.0                       9
 60.0      4.0                      15
 61.0      4.0                       8
 62.0      4.0                       9
 63.0      4.0                      11
 64.0      4.0                       9
 65.0      4.0                      11
 66.0      4.0                       8
 67.0      4.0                       7
 68.0      4.0                       9
 69.0      4.0                       8
 70.0      4.0                      14
 71.0      4.0                       6
 72.0      4.0                       7
 73.0      4.0                       6
 74.0      4.0                       8
 75.0      5.0                       7
 76.0      5.0                       2
 77.0      5.0                       6
 78.0      5.0                       8
 79.0      5.0                       4
 80.0      5.0                       6
 81.0      5.0                       6
 82.0      5.0                       3
 83.0      5.0                       7
 84.0      5.0                       6
 85.0      5.0                       6
 86.0      5.0                       6
 87.0      5.0                       7
 88.0      5.0                       3
 89.0      5.0                       3
 90.0      6.0                       7
 91.0      6.0                       3
 93.0      6.0                       2
 94.0      6.0                       2
 95.0      6.0                       7
 96.0      6.0                       2
 97.0      6.0                       5
 98.0      6.0                       7
 99.0      6.0                       6
 100.0     6.0                       3
 101.0     6.0                       1
 102.0     6.0                       1
 103.0     6.0                       6
 104.0     6.0                       4
 106.0     7.0                       2
 107.0     7.0                       3
 108.0     7.0                       4
 109.0     7.0                       2
 110.0     7.0                       5
 111.0     7.0                       3
 112.0     7.0                       1
 113.0     7.0                       5
 114.0     7.0                       4
 115.0     7.0                       1
 116.0     7.0                       3
 117.0     7.0                       4
 118.0     7.0                       2
 119.0     7.0                       3
 120.0     8.0                       2
 121.0     8.0                       5
 122.0     8.0                       1
 123.0     8.0                       2
 124.0     8.0                       4
 125.0     8.0                       2
 126.0     8.0                       1
 128.0     8.0                       2
 129.0     8.0                       1
 130.0     8.0                       1
 131.0     8.0                       1
 132.0     8.0                       2
 133.0     8.0                       1
 134.0     8.0                       1
 137.0     9.0                       1
 138.0     9.0                       2
 139.0     9.0                       1
 140.0     9.0                       4
 141.0     9.0                       2
 143.0     9.0                       2
 144.0     9.0                       2
 145.0     9.0                       1
 146.0     9.0                       2
 147.0     9.0                       1
 149.0     9.0                       3
 150.0     10.0                      5
 151.0     10.0                      1
 153.0     10.0                      1
 155.0     10.0                      3
 156.0     10.0                      2
 157.0     10.0                      1
 158.0     10.0                      4
 159.0     10.0                      1
 160.0     10.0                      2
 161.0     10.0                      1
 162.0     10.0                      2
 164.0     10.0                      1
 165.0     11.0                      2
 168.0     11.0                      2
 170.0     11.0                      2
 171.0     11.0                      2
 172.0     11.0                      2
 174.0     11.0                      1
 177.0     11.0                      2
 179.0     11.0                      1
 180.0     12.0                      3
 181.0     12.0                      1
 183.0     12.0                      1
 184.0     12.0                      1
 185.0     12.0                      1
 187.0     12.0                      1
 189.0     12.0                      2
 191.0     12.0                      1
 193.0     12.0                      1
 196.0     12.0                      1
 197.0     12.0                      1
 198.0     12.0                      1
 199.0     12.0                      1
 205.0     12.0                      1
 207.0     12.0                      1
 208.0     12.0                      1
 214.0     12.0                      1
 220.0     12.0                      1
 221.0     12.0                      1
 223.0     12.0                      1
 224.0     12.0                      2
 233.0     12.0                      1
 238.0     12.0                      1
 241.0     12.0                      1
 248.0     12.0                      1
 263.0     12.0                      1
 267.0     12.0                      2
 282.0     12.0                      1
 289.0     12.0                      1
 308.0     12.0                      1
 330.0     12.0                      1
 339.0     12.0                      1
 346.0     12.0                      1
 365.0     12.0                      1
 376.0     12.0                      1
 400.0     12.0                      1
 403.0     12.0                      1
 460.0     12.0                      1
 600.0     12.0                      1
 732.0     12.0                      1
 988.0     12.0                      1
dtype: int64

In [65]:
pd.pivot_table(adf,
               index = ['Year', 'Quarter',],
               values = 'ArrTime',
               #aggfunc = 'sum',
               columns = 'DepartureDelayGroups',
               margins = True
              ).head(3) #cambias a tail y presenta los ultimos. tail son los ultimos

DepartureDelayGroups  -2.0         -1.0          0.0          1.0  \
Year Quarter
1987 4                 NaN  1603.142857  1433.685714  1244.571429
1988 1                 NaN  1416.555556  1536.023810  1324.833333
     2                 NaN  1396.000000  1443.195122  1381.000000

DepartureDelayGroups          2.0     3.0     4.0     5.0     6.0     7.0  \
Year Quarter
1987 4                2307.000000  1780.0     NaN     NaN     NaN     NaN
1988 1                        NaN  1294.5  1821.0  1850.0  2246.0  1337.0
     2                1738.333333  1929.0     NaN   130.0     NaN     NaN

DepartureDelayGroups  8.0  9.0    10.0    11.0  12.0          All
Year Quarter
1987 4                NaN  NaN     NaN     NaN   NaN  1461.153846
1988 1                NaN  NaN     NaN     NaN   NaN  1508.793651
     2                NaN  NaN  1150.0  2233.0   NaN  1440.032258